const $ = selector => document.querySelector(selector);
const state = { user: JSON.parse(localStorage.getItem('credmais_user') || 'null'), clients: JSON.parse(localStorage.getItem('credmais_clients') || '[]'), loans: JSON.parse(localStorage.getItem('credmais_loans') || '[]') };
const money = value => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const digits = value => String(value || '').replace(/\D/g, '');
const initials = name => name.split(' ').slice(0, 2).map(part => part[0]).join('').toUpperCase();
const save = () => { localStorage.setItem('credmais_clients', JSON.stringify(state.clients)); localStorage.setItem('credmais_loans', JSON.stringify(state.loans)); };
const formatCpf = value => digits(value).slice(0, 11).replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d{1,2})$/, '$1-$2');
const formatPhone = value => { const number = digits(value).slice(0, 11); return number.length <= 10 ? number.replace(/(\d{2})(\d)/, '($1) $2').replace(/(\d{4})(\d)/, '$1-$2') : number.replace(/(\d{2})(\d)/, '($1) $2').replace(/(\d{5})(\d)/, '$1-$2'); };
const dateFor = (loan, installment) => { const date = new Date(`${loan.dueDate}T12:00`); date.setDate(date.getDate() + Number(loan.frequency || 30) * installment); return date; };
const dueStatus = date => { const today = new Date(); today.setHours(0, 0, 0, 0); const due = new Date(date); due.setHours(0, 0, 0, 0); return due < today ? 'Vencida' : due.getTime() === today.getTime() ? 'Vence hoje' : 'A vencer'; };
const formatFrequency = days => Number(days) === 30 ? 'Mensal' : `A cada ${days} dias`;
function toast(message) { const element = $('#toast'); element.textContent = message; element.classList.add('show'); setTimeout(() => element.classList.remove('show'), 2800); }
function setAuth(view) { $('#loginForm').hidden = view !== 'login'; $('#registerForm').hidden = view !== 'register'; }
function showApp() { $('#authView').hidden = true; $('#appView').hidden = false; $('#userName').textContent = state.user.name; $('#greetingName').textContent = state.user.name.split(' ')[0]; $('#initials').textContent = initials(state.user.name); render(); }
function login(event) { event.preventDefault(); const account = JSON.parse(localStorage.getItem('credmais_account') || 'null'); if (!account || account.email !== $('#loginEmail').value || account.password !== $('#loginPassword').value) return toast('E-mail ou senha incorretos.'); state.user = { name: account.name, email: account.email }; localStorage.setItem('credmais_user', JSON.stringify(state.user)); showApp(); }
function register(event) { event.preventDefault(); const account = { name: $('#registerName').value.trim(), email: $('#registerEmail').value.trim(), password: $('#registerPassword').value }; localStorage.setItem('credmais_account', JSON.stringify(account)); state.user = { name: account.name, email: account.email }; localStorage.setItem('credmais_user', JSON.stringify(state.user)); showApp(); toast('Conta criada. Boas-vindas!'); }
function resetClientForm() { $('#clientForm').reset(); $('#clientId').value = ''; $('#clientModalEyebrow').textContent = 'NOVO CADASTRO'; $('#clientModalTitle').textContent = 'Adicionar cliente'; $('#clientSaveBtn').textContent = 'Salvar cliente'; }
function resetLoanForm() { $('#loanForm').reset(); $('#loanId').value = ''; $('#loanInterest').value = '10'; $('#loanFrequency').value = '30'; $('#loanInstallments').value = '6'; const date = new Date(); date.setDate(date.getDate() + 30); $('#loanDueDate').value = date.toISOString().slice(0, 10); $('#loanModalEyebrow').textContent = 'NOVA OPERAÇÃO'; $('#loanModalTitle').textContent = 'Novo empréstimo'; $('#loanSaveBtn').textContent = 'Confirmar empréstimo'; }
function openModal(id) { if (id === 'loanModal' && !state.clients.length) { toast('Cadastre um cliente antes de criar um empréstimo.'); return openClient(); } $('#modalBackdrop').hidden = false; $(`#${id}`).hidden = false; }
function closeModals() { document.querySelectorAll('.modal').forEach(modal => { modal.hidden = true; }); $('#modalBackdrop').hidden = true; }
function openClient(id) { resetClientForm(); if (id) { const client = state.clients.find(item => item.id === id); if (!client) return; $('#clientId').value = client.id; $('#clientName').value = client.name; $('#clientCpf').value = client.cpf; $('#clientPhone').value = client.phone; $('#clientEmail').value = client.email || ''; $('#clientNote').value = client.note || ''; $('#clientModalEyebrow').textContent = 'EDITAR CLIENTE'; $('#clientModalTitle').textContent = 'Atualizar cadastro'; $('#clientSaveBtn').textContent = 'Salvar alterações'; } openModal('clientModal'); }
function prepareLoan(id) { $('#loanClient').innerHTML = state.clients.map(client => `<option value="${client.id}">${client.name}</option>`).join(''); if (!id) resetLoanForm(); else { const loan = state.loans.find(item => item.id === id); if (!loan) return; $('#loanId').value = loan.id; $('#loanClient').value = loan.clientId; $('#loanAmount').value = loan.amount; $('#loanInterest').value = loan.rate * 100; $('#loanInstallments').value = loan.installments; $('#loanFrequency').value = loan.frequency || 30; $('#loanDueDate').value = loan.dueDate; $('#loanModalEyebrow').textContent = 'EDITAR OPERAÇÃO'; $('#loanModalTitle').textContent = 'Atualizar empréstimo'; $('#loanSaveBtn').textContent = 'Salvar alterações'; } calc(); }
function openLoan(id) { if (!state.clients.length) return openModal('loanModal'); $('#modalBackdrop').hidden = false; $('#loanModal').hidden = false; prepareLoan(id); }
function setPage(page) { document.querySelectorAll('.page').forEach(item => item.classList.toggle('active', item.id === `${page}Page`)); document.querySelectorAll('[data-page]').forEach(item => item.classList.toggle('active', item.dataset.page === page)); $('#pageTitle').textContent = { dashboard: 'Visão geral', clients: 'Clientes', loans: 'Empréstimos' }[page]; $('.sidebar').classList.remove('open'); render(); }
function render() { renderStats(); renderClients(); renderLoans(); }
function renderStats() { const lent = state.loans.reduce((sum, loan) => sum + loan.amount, 0); const receivable = state.loans.reduce((sum, loan) => sum + loan.total, 0); const interest = Math.max(0, receivable - lent); $('#statLent').textContent = money(lent); $('#statReceivable').textContent = money(receivable); $('#statClients').textContent = state.clients.length; $('#statLoans').textContent = state.loans.length; $('#chartTotal').textContent = money(receivable); $('#legendLent').textContent = money(lent); $('#legendInterest').textContent = money(interest); $('#financeChart').style.setProperty('--lent-percent', `${receivable ? Math.round((lent / receivable) * 100) : 100}%`); const recent = $('#recentLoans'); if (!state.loans.length) { recent.className = 'empty'; recent.innerHTML = '<span>◫</span><h4>Nenhum empréstimo ainda</h4><p>Comece cadastrando um novo empréstimo.</p><button class="outline add-loan">Criar empréstimo</button>'; } else { recent.className = 'loan-list'; recent.innerHTML = state.loans.slice(-4).reverse().map(loanRow).join(''); } renderDueLoans(); }
function renderDueLoans() { const pending = state.loans.flatMap(loan => Array.from({ length: loan.installments }, (_, index) => ({ loan, index, date: dateFor(loan, index) }))).filter(item => dueStatus(item.date) !== 'A vencer').sort((a, b) => b.date - a.date).slice(0, 4); $('#dueLoans').innerHTML = pending.length ? pending.map(({ loan, index, date }) => { const client = state.clients.find(item => item.id === loan.clientId); return `<div class="due-item"><div><b>${client?.name || 'Cliente removido'}</b><span>${dueStatus(date)} · ${money(loan.installment)}</span></div><button class="whatsapp" data-whatsapp="${loan.id}" data-installment="${index}">Cobrar</button></div>`; }).join('') : '<div class="empty compact"><span>✓</span><h4>Tudo em dia</h4><p>Não há cobranças vencidas ou para hoje.</p></div>'; }
function renderClients() { const term = ($('#clientSearch')?.value || '').toLowerCase(); const clients = state.clients.filter(client => [client.name, client.cpf, client.phone].join(' ').toLowerCase().includes(term)); $('#clientCount').textContent = `${clients.length} cliente${clients.length === 1 ? '' : 's'}`; $('#clientsList').innerHTML = clients.length ? clients.map(client => { const count = state.loans.filter(loan => loan.clientId === client.id).length; return `<article class="client-card"><div class="client-card-head"><div class="client-avatar">${initials(client.name)}</div><button class="edit-button" data-edit-client="${client.id}" aria-label="Editar ${client.name}">✎</button></div><h3>${client.name}</h3><p>${client.phone || client.email || 'Sem contato informado'}</p><footer><span>${count} empréstimo${count === 1 ? '' : 's'}</span><span class="badge">Ativo</span></footer></article>`; }).join('') : '<div class="empty"><span>♙</span><h4>Nenhum cliente encontrado</h4><p>Cadastre seu primeiro cliente para começar.</p><button class="outline" data-open-client>Novo cliente</button></div>'; }
function loanRow(loan) { const client = state.clients.find(item => item.id === loan.clientId) || { name: 'Cliente removido' }; return `<article class="loan-row"><div><h3>${client.name}</h3><p>${loan.installments}x de ${money(loan.installment)} · ${formatFrequency(loan.frequency || 30)}</p></div><div class="loan-extra"><p>Emprestado</p><b>${money(loan.amount)}</b></div><div class="loan-extra"><p>1º vencimento</p><b>${dateFor(loan, 0).toLocaleDateString('pt-BR')}</b></div><div class="loan-value">${money(loan.total)}</div><button data-details="${loan.id}">Detalhes →</button></article>`; }
function renderLoans() { $('#loansList').innerHTML = state.loans.length ? state.loans.slice().reverse().map(loanRow).join('') : '<div class="empty"><span>◫</span><h4>Nenhum empréstimo cadastrado</h4><p>Crie uma operação quando estiver pronto.</p><button class="outline add-loan">Criar empréstimo</button></div>'; }
function calc() { const amount = Number($('#loanAmount').value) || 0; const rate = (Number($('#loanInterest').value) || 0) / 100; const periods = Number($('#loanInstallments').value) || 1; const total = amount * Math.pow(1 + rate, periods); $('#calcInterest').textContent = money(total - amount); $('#calcTotal').textContent = money(total); $('#calcInstallment').textContent = money(total / periods); return { amount, rate, periods, total }; }
function saveClient(event) { event.preventDefault(); const cpf = digits($('#clientCpf').value), phone = digits($('#clientPhone').value); if (cpf.length !== 11) return toast('Informe um CPF com 11 números.'); if (phone.length < 10 || phone.length > 11) return toast('Informe um telefone válido com DDD.'); const client = { id: $('#clientId').value || crypto.randomUUID(), name: $('#clientName').value.trim(), cpf: formatCpf(cpf), phone: formatPhone(phone), email: $('#clientEmail').value.trim(), note: $('#clientNote').value.trim() }; const index = state.clients.findIndex(item => item.id === client.id); if (index >= 0) state.clients[index] = client; else state.clients.push(client); save(); closeModals(); render(); toast(index >= 0 ? 'Cliente atualizado com sucesso.' : 'Cliente cadastrado com sucesso.'); }
function saveLoan(event) { event.preventDefault(); const calculation = calc(); if (!calculation.amount) return toast('Informe o valor emprestado.'); const loan = { id: $('#loanId').value || crypto.randomUUID(), clientId: $('#loanClient').value, amount: calculation.amount, rate: calculation.rate, installments: calculation.periods, frequency: Number($('#loanFrequency').value), total: calculation.total, installment: calculation.total / calculation.periods, dueDate: $('#loanDueDate').value, createdAt: new Date().toISOString() }; const index = state.loans.findIndex(item => item.id === loan.id); if (index >= 0) state.loans[index] = loan; else state.loans.push(loan); save(); closeModals(); setPage('loans'); toast(index >= 0 ? 'Empréstimo atualizado com sucesso.' : 'Empréstimo cadastrado com sucesso.'); }
function details(id) { const loan = state.loans.find(item => item.id === id), client = state.clients.find(item => item.id === loan.clientId); const items = Array.from({ length: loan.installments }, (_, index) => { const date = dateFor(loan, index), status = dueStatus(date); return `<div class="installment"><span>Parcela ${index + 1} de ${loan.installments} · ${date.toLocaleDateString('pt-BR')} <em class="due ${status === 'A vencer' ? 'future' : 'late'}">${status}</em></span><div><b>${money(loan.installment)}</b><button class="whatsapp" data-whatsapp="${loan.id}" data-installment="${index}">WhatsApp</button></div></div>`; }).join(''); $('#loanDetails').innerHTML = `<div class="details-head"><div><span class="eyebrow">EMPRÉSTIMO</span><h2>${client?.name || 'Cliente'}</h2><p class="muted">Juros de ${(loan.rate * 100).toLocaleString('pt-BR')}% a cada ${loan.frequency || 30} dias</p></div><button class="outline small" data-edit-loan="${loan.id}">Editar</button></div><div class="details-summary"><div><span>Valor emprestado</span><b>${money(loan.amount)}</b></div><div><span>Juros totais</span><b>${money(loan.total - loan.amount)}</b></div><div><span>Total a receber</span><b>${money(loan.total)}</b></div></div><h3>Parcelas</h3><p class="muted charge-note">Abra o WhatsApp com a cobrança completa e pronta para envio.</p><div class="installment-list">${items}</div>`; openModal('detailsModal'); }
function openWhatsApp(loanId, installmentIndex) { const loan = state.loans.find(item => item.id === loanId), client = state.clients.find(item => item.id === loan.clientId), phone = digits(client?.phone); if (phone.length < 10) return toast('Este cliente não possui um telefone válido.'); const date = dateFor(loan, Number(installmentIndex)); const message = `Olá, ${client.name}!\n\nLembramos que a parcela ${Number(installmentIndex) + 1}/${loan.installments} do seu empréstimo ${dueStatus(date).toLowerCase()} em ${date.toLocaleDateString('pt-BR')}.\n\nValor da parcela: ${money(loan.installment)}\nFrequência: ${formatFrequency(loan.frequency || 30)}\nValor total do empréstimo: ${money(loan.total)}\n\nPor favor, entre em contato para combinarmos o pagamento. Obrigado!`; window.open(`https://wa.me/55${phone}?text=${encodeURIComponent(message)}`, '_blank', 'noopener'); }
function toggleTheme() { document.body.classList.toggle('dark'); const dark = document.body.classList.contains('dark'); localStorage.setItem('credmais_theme', dark ? 'dark' : 'light'); $('#themeToggle').innerHTML = `${dark ? '☾' : '☀'} <span>Modo ${dark ? 'escuro' : 'claro'}</span>`; $('#headerTheme').textContent = dark ? '☀' : '☾'; $('#bottomTheme').innerHTML = `<i>${dark ? '☀' : '☾'}</i><span>Tema</span>`; }
$('#login').addEventListener('submit', login); $('#register').addEventListener('submit', register); $('#clientForm').addEventListener('submit', saveClient); $('#loanForm').addEventListener('submit', saveLoan); $('#clientCpf').addEventListener('input', event => { event.target.value = formatCpf(event.target.value); }); $('#clientPhone').addEventListener('input', event => { event.target.value = formatPhone(event.target.value); }); ['loanAmount', 'loanInterest', 'loanInstallments'].forEach(id => $(`#${id}`).addEventListener('input', calc)); $('#clientSearch').addEventListener('input', renderClients); $('#addClientBtn').onclick = () => openClient(); $('#menuBtn').onclick = () => $('.sidebar').classList.toggle('open'); $('#themeToggle').onclick = toggleTheme; $('#headerTheme').onclick = toggleTheme; $('#bottomTheme').onclick = toggleTheme; $('#logoutBtn').onclick = () => { localStorage.removeItem('credmais_user'); location.reload(); }; $('#modalBackdrop').onclick = closeModals; document.querySelectorAll('[data-auth]').forEach(button => { button.onclick = () => setAuth(button.dataset.auth); }); document.querySelectorAll('.nav-link[data-page], .bottom-link[data-page]').forEach(button => { button.onclick = () => setPage(button.dataset.page); }); document.addEventListener('click', event => { const button = event.target.closest('button'); if (!button) return; if (button.classList.contains('add-loan')) openLoan(); if (button.dataset.close) closeModals(); if (button.dataset.pageLink) setPage(button.dataset.pageLink); if (button.dataset.details) details(button.dataset.details); if (button.dataset.whatsapp) openWhatsApp(button.dataset.whatsapp, button.dataset.installment); if (button.dataset.editClient) openClient(button.dataset.editClient); if (button.dataset.editLoan) { closeModals(); openLoan(button.dataset.editLoan); } if (button.hasAttribute('data-open-client')) openClient(); }); if (localStorage.getItem('credmais_theme') === 'dark') toggleTheme(); if (state.user) showApp();
