const $ = s => document.querySelector(s);
const state = { user: JSON.parse(localStorage.getItem('credmais_user') || 'null'), clients: JSON.parse(localStorage.getItem('credmais_clients') || '[]'), loans: JSON.parse(localStorage.getItem('credmais_loans') || '[]') };
const money = n => Number(n || 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const save = () => { localStorage.setItem('credmais_clients',JSON.stringify(state.clients)); localStorage.setItem('credmais_loans',JSON.stringify(state.loans)); };
const initials = name => name.split(' ').slice(0,2).map(n=>n[0]).join('').toUpperCase();
const digits = value => value.replace(/\D/g,'');
const formatCpf = value => digits(value).slice(0,11).replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d{1,2})$/,'$1-$2');
const formatPhone = value => { const number=digits(value).slice(0,11); return number.length<=10?number.replace(/(\d{2})(\d)/,'($1) $2').replace(/(\d{4})(\d)/,'$1-$2'):number.replace(/(\d{2})(\d)/,'($1) $2').replace(/(\d{5})(\d)/,'$1-$2'); };
const dueDate = (loan,index) => { const date=new Date(loan.dueDate+'T12:00');date.setMonth(date.getMonth()+index);return date; };
const dueLabel = date => { const today=new Date();today.setHours(0,0,0,0);const due=new Date(date);due.setHours(0,0,0,0);return due<today?'Vencida':due.getTime()===today.getTime()?'Vence hoje':'A vencer'; };
function toast(message){ const t=$('#toast'); t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800); }
function setAuth(view){ $('#loginForm').hidden=view!=='login';$('#registerForm').hidden=view!=='register'; }
function showApp(){ $('#authView').hidden=true;$('#appView').hidden=false; const name=state.user.name;$('#userName').textContent=name;$('#greetingName').textContent=name.split(' ')[0];$('#initials').textContent=initials(name);render(); }
function login(e){e.preventDefault();const email=$('#loginEmail').value, pass=$('#loginPassword').value;const stored=JSON.parse(localStorage.getItem('credmais_account')||'null');if(!stored||stored.email!==email||stored.password!==pass)return toast('E-mail ou senha incorretos.');state.user={name:stored.name,email};localStorage.setItem('credmais_user',JSON.stringify(state.user));showApp();}
function register(e){e.preventDefault();const account={name:$('#registerName').value.trim(),email:$('#registerEmail').value.trim(),password:$('#registerPassword').value};localStorage.setItem('credmais_account',JSON.stringify(account));state.user={name:account.name,email:account.email};localStorage.setItem('credmais_user',JSON.stringify(state.user));showApp();toast('Conta criada. Boas-vindas!');}
function openModal(id){ if(id==='loanModal'&&!state.clients.length){toast('Cadastre um cliente antes de criar um empréstimo.');return openModal('clientModal');}$('#modalBackdrop').hidden=false;$('#'+id).hidden=false;if(id==='loanModal')prepareLoan(); }
function closeModals(){document.querySelectorAll('.modal').forEach(x=>x.hidden=true);$('#modalBackdrop').hidden=true;}
function setPage(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-link[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#'+page+'Page').classList.add('active');$('#pageTitle').textContent={dashboard:'Visão geral',clients:'Clientes',loans:'Empréstimos'}[page];$('.sidebar').classList.remove('open');render();}
function render(){renderStats();renderClients();renderLoans();}
function renderStats(){const active=state.loans;const lent=active.reduce((s,l)=>s+l.amount,0), receivable=active.reduce((s,l)=>s+l.total,0);$('#statLent').textContent=money(lent);$('#statReceivable').textContent=money(receivable);$('#statClients').textContent=state.clients.length;$('#statLoans').textContent=active.length;const recent=$('#recentLoans');if(!active.length){recent.className='empty';recent.innerHTML='<span>◫</span><h4>Nenhum empréstimo ainda</h4><p>Comece cadastrando um novo empréstimo.</p><button class="outline add-loan">Criar empréstimo</button>';return}recent.className='loan-list';recent.innerHTML=active.slice(-4).reverse().map(loanRow).join('');}
function renderClients(){const term=($('#clientSearch')?.value||'').toLowerCase();const found=state.clients.filter(c=>[c.name,c.cpf,c.phone].join(' ').toLowerCase().includes(term));$('#clientCount').textContent=`${found.length} cliente${found.length===1?'':'s'}`;$('#clientsList').innerHTML=found.length?found.map(c=>{const count=state.loans.filter(l=>l.clientId===c.id).length;return `<article class="client-card"><div class="client-avatar">${initials(c.name)}</div><h3>${c.name}</h3><p>${c.phone||c.email||'Sem contato informado'}</p><footer><span>${count} empréstimo${count===1?'':'s'}</span><span class="badge">Ativo</span></footer></article>`}).join(''):'<div class="empty"><span>♙</span><h4>Nenhum cliente encontrado</h4><p>Cadastre seu primeiro cliente para começar.</p></div>';}
function loanRow(l){const c=state.clients.find(x=>x.id===l.clientId)||{name:'Cliente removido'};return `<article class="loan-row"><div><h3>${c.name}</h3><p>${l.installments}x de ${money(l.installment)}</p></div><div class="loan-extra"><p>Emprestado</p><b>${money(l.amount)}</b></div><div class="loan-extra"><p>Vencimento</p><b>${new Date(l.dueDate+'T12:00').toLocaleDateString('pt-BR')}</b></div><div class="loan-value">${money(l.total)}</div><button data-details="${l.id}">Detalhes →</button></article>`;}
function renderLoans(){const el=$('#loansList');el.innerHTML=state.loans.length?state.loans.slice().reverse().map(loanRow).join(''):'<div class="empty"><span>◫</span><h4>Nenhum empréstimo cadastrado</h4><p>Crie uma operação quando estiver pronto.</p><button class="outline add-loan">Criar empréstimo</button></div>';}
function prepareLoan(){const select=$('#loanClient');select.innerHTML=state.clients.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');if(!$('#loanDueDate').value){let d=new Date();d.setMonth(d.getMonth()+1);$('#loanDueDate').value=d.toISOString().slice(0,10)};calc();}
function calc(){const amount=Number($('#loanAmount').value)||0, rate=(Number($('#loanInterest').value)||0)/100, months=Number($('#loanInstallments').value)||1;const total=amount*Math.pow(1+rate,months), interest=total-amount;$('#calcInterest').textContent=money(interest);$('#calcTotal').textContent=money(total);$('#calcInstallment').textContent=money(total/months);return{amount,rate,months,total,interest};}
function addClient(e){e.preventDefault();const cpf=digits($('#clientCpf').value),phone=digits($('#clientPhone').value);if(cpf.length!==11){$('#clientCpf').focus();return toast('Informe um CPF com 11 números.');}if(phone.length<10||phone.length>11){$('#clientPhone').focus();return toast('Informe um telefone válido com DDD.');}state.clients.push({id:crypto.randomUUID(),name:$('#clientName').value.trim(),cpf:formatCpf(cpf),phone:formatPhone(phone),email:$('#clientEmail').value.trim(),note:$('#clientNote').value.trim()});save();e.target.reset();closeModals();render();toast('Cliente cadastrado com sucesso.');}
function addLoan(e){e.preventDefault();const v=calc();if(!v.amount)return toast('Informe o valor emprestado.');state.loans.push({id:crypto.randomUUID(),clientId:$('#loanClient').value,amount:v.amount,rate:v.rate,installments:v.months,total:v.total,installment:v.total/v.months,dueDate:$('#loanDueDate').value,createdAt:new Date().toISOString()});save();e.target.reset();closeModals();setPage('loans');toast('Empréstimo cadastrado com sucesso.');}
function details(id){const l=state.loans.find(x=>x.id===id),c=state.clients.find(x=>x.id===l.clientId);const items=Array.from({length:l.installments},(_,i)=>{const d=dueDate(l,i),status=dueLabel(d);return `<div class="installment"><span>Parcela ${i+1} de ${l.installments} · ${d.toLocaleDateString('pt-BR')} <em class="due ${status==='A vencer'?'future':'late'}">${status}</em></span><div><b>${money(l.installment)}</b><button class="whatsapp" data-whatsapp="${l.id}" data-installment="${i}">WhatsApp</button></div></div>`}).join('');$('#loanDetails').innerHTML=`<div class="details-head"><span class="eyebrow">EMPRÉSTIMO</span><h2>${c?.name||'Cliente'}</h2><p class="muted">Juros de ${(l.rate*100).toLocaleString('pt-BR')}% ao mês</p></div><div class="details-summary"><div><span>Valor emprestado</span><b>${money(l.amount)}</b></div><div><span>Juros totais</span><b>${money(l.total-l.amount)}</b></div><div><span>Total a receber</span><b>${money(l.total)}</b></div></div><h3>Parcelas</h3><p class="muted charge-note">Envie a cobrança pelo WhatsApp quando a parcela vencer.</p><div class="installment-list">${items}</div>`;openModal('detailsModal');}
function openWhatsApp(loanId,installmentIndex){const loan=state.loans.find(l=>l.id===loanId),client=state.clients.find(c=>c.id===loan.clientId),date=dueDate(loan,Number(installmentIndex));const phone=digits(client?.phone||'');if(phone.length<10)return toast('Este cliente não possui um telefone válido.');const message=`Olá, ${client.name}!\n\nLembramos que a parcela ${Number(installmentIndex)+1}/${loan.installments} do seu empréstimo venceu em ${date.toLocaleDateString('pt-BR')}.\n\nValor da parcela: ${money(loan.installment)}\nValor total do empréstimo: ${money(loan.total)}\n\nPor favor, entre em contato para combinarmos o pagamento. Obrigado!`;window.open(`https://wa.me/55${phone}?text=${encodeURIComponent(message)}`,'_blank','noopener');}
$('#login').addEventListener('submit',login);$('#register').addEventListener('submit',register);document.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>setAuth(b.dataset.auth));$('#logoutBtn').onclick=()=>{localStorage.removeItem('credmais_user');location.reload()};$('#addClientBtn').onclick=()=>openModal('clientModal');document.querySelectorAll('.add-loan').forEach(b=>b.onclick=()=>openModal('loanModal'));document.addEventListener('click',e=>{if(e.target.closest('.add-loan'))openModal('loanModal');if(e.target.dataset.close||e.target===$('#modalBackdrop'))closeModals();if(e.target.dataset.pageLink)setPage(e.target.dataset.pageLink);if(e.target.dataset.details)details(e.target.dataset.details);if(e.target.dataset.whatsapp)openWhatsApp(e.target.dataset.whatsapp,e.target.dataset.installment);});document.querySelectorAll('.nav-link[data-page]').forEach(b=>b.onclick=()=>setPage(b.dataset.page));$('#clientForm').addEventListener('submit',addClient);$('#loanForm').addEventListener('submit',addLoan);['loanAmount','loanInterest','loanInstallments'].forEach(id=>$('#'+id).addEventListener('input',calc));$('#clientCpf').addEventListener('input',e=>e.target.value=formatCpf(e.target.value));$('#clientPhone').addEventListener('input',e=>e.target.value=formatPhone(e.target.value));$('#clientSearch').addEventListener('input',renderClients);function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('credmais_theme',document.body.classList.contains('dark')?'dark':'light');const dark=document.body.classList.contains('dark');$('#themeToggle').innerHTML=(dark?'☾':'☀')+' <span>Modo '+(dark?'escuro':'claro')+'</span>';$('#headerTheme').textContent=dark?'☀':'☾';}$('#themeToggle').onclick=toggleTheme;$('#headerTheme').onclick=toggleTheme;$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');if(localStorage.getItem('credmais_theme')==='dark')toggleTheme();if(state.user)showApp();
